version: '2'
services:
    ebanking-app:
        image: ebanking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ebanking-postgresql:5432/Ebanking
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ebanking-postgresql:
        extends:
            file: postgresql.yml
            service: ebanking-postgresql
